--CREATE PROCEDURE [dbo].[CSP_Login]
--	@UserName NVARCHAR(80),
--	@Email NVARCHAR(384),
--	@Passwd NVARCHAR(20)
--AS
--BEGIN
--	SELECT [Id], [FirstName], [LastName],[UserName], [Email] , [BirthDate], [Passwd] 
--	FROM [User]
--	WHERE	
--			[UserName] = @UserName
--	AND
--			[Email] = @Email 
--	AND		
--			[Passwd] = dbo.CSF_HashPassword(@Passwd);
--	RETURN 0
--END
